[Blender]
blender_executable_path = C:\Program Files\Blender Foundation\Blender 4.1\blender.exe
; blender_executable_path = /Applications/Blender.app/Contents/MacOS/Blender (macOS)
; blender_executable_path = /usr/bin/blender (Linux)

; Global
[RenderSettings]
resolution_x = 256
resolution_y = 256
rotation_steps = 8
rotation_axis = Z
eevee_taa_render_samples = 16
film_transparent = True
debug_no_transparent_background = False
verbose_render_loop = True

[Animation] ; Global Animation
anim_start_frame = 0
anim_end_frame = 39

[Camera] ; Global Camera
camera_distance = 15.0
camera_elevation_degrees = 20.0
camera_target_z_offset = 0.9
ortho_scale_padding_factor = 3
ortho_scale_fallback = 4.0
key_light_energy = 3.0
key_light_angle_softness = 10.0
fill_light_energy = 1.5
fill_light_angle_softness = 15.0

; --------------------------------------------------------------------
; "Walking" Animationen
; --------------------------------------------------------------------
[RenderSettingsWalking]
resolution_x = 256
resolution_y = 256
rotation_steps = 8
rotation_axis = Z

[AnimationWalking]
; anim_start_frame = 0
; anim_end_frame = 30

[CameraWalking]
camera_distance = 15.0
camera_elevation_degrees = 20.0
camera_target_z_offset = 0.9
ortho_scale_padding_factor = 3

[ModelProcessingWalking]
desired_model_height = 2

; --------------------------------------------------------------------
; "Idle" Animationen
; --------------------------------------------------------------------
[RenderSettingsIdle]
rotation_steps = 1

[AnimationIdle]
anim_start_frame = 0
anim_end_frame = 5

[CameraIdle]
camera_distance = 15.0
camera_elevation_degrees = 20.0
camera_target_z_offset = 0.9
ortho_scale_padding_factor = 3

; ModelProcessingIdle

; --------------------------------------------------------------------
; "Fly" Animationen
; --------------------------------------------------------------------
[RenderSettingsFly]
rotation_steps = 8 

; AnimationFly
anim_start_frame = 0
anim_end_frame = 25

[CameraFly]
camera_distance = 15.0
camera_elevation_degrees = 20.0
camera_target_z_offset = 0.9
ortho_scale_padding_factor = 5

; ModelProcessingFly
; desired_model_height = 2

; --------------------------------------------------------------------
; Global ModelProcessing (Fallback)
; --------------------------------------------------------------------
[ModelProcessing]
desired_model_height = 2